version: "3"
services:
  aplikasi:
    image: myapp:test
    ports:
    - 80:8080
    user: root
    volumes:
      - "maven-repo:/root/.m2"
      - type: bind
        source: /apps/testing/testdocker
        target: /app
