version: "3.8"
services:
  aplikasi:
    image: myapp:test
    ports:
    - 80:8080
    command: chmod +x ./mvnw
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: /apps/testing/testdocker
        target: /app
volumes:
  maven-repo:
    external:
      name: maven-repo